version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: './bin/rails server'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - $PWD:/opt/app
      - bundle_cache:/gems
    env_file:
      - ./env
volumes:
  bundle_cache:
